=== HDFGroup/hdf5-json/h5json/schema/hdf5.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "$id": "https://hdfgroup.org/schemas/hdf5/json/hdf5.schema.json",
    "title": "HDF5 File JSON Schema",
    "description": "JSON Schema describing HDF5 file.",
    "type": "object",
    "required": [
        "apiVersion",
        "root"
    ],
    "properties": {
        "apiVersion": {
            "description": "HDF5/JSON version identifier.",
            "type": "string",
            "enum": [
                "1.0.0",
                "1.1.0",
                "1.1.1"
            ]
        },
        "id": {
            "description": "HDF5 file identifier.",
            "type": "string"
        },
        "root": {
            "description": "Unique identifier of the HDF5 root group.",
            "type": "string"
        },
        "created": {
            "description": "UTC date/time of file creation.",
            "type": "string",
            "format": "date-time"
        },
        "lastModified": {
            "description": "UTC date/time of last file content modification.",
            "type": "string",
            "format": "date-time"
        },
        "userblock": {
            "description": "HDF5 file user block.",
            "type": "array",
            "items": {
                "type": "integer"
            },
            "minItems": 1
        },
        "userblockSize": {
            "description": "HDF5 file user block size.",
            "type": "integer",
            "minimum": 512,
            "multipleOf": 2
        },
        "driverInfo": {
            "description": "HDF5 file driver information.",
            "oneOf": [
                {
                    "type": "object",
                    "properties": {
                        "memberSize": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    }
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "properties": {
                            "dataMap": {
                                "type": "string",
                                "enum": [
                                    "H5FD_MEM_SUPER",
                                    "H5FD_MEM_BTREE",
                                    "H5FD_MEM_DRAW",
                                    "H5FD_MEM_GHEAP",
                                    "H5FD_MEM_LHEAP",
                                    "H5FD_MEM_OHDR"
                                ]
                            },
                            "fileName": {
                                "type": "string"
                            },
                            "address": {
                                "type": "integer",
                                "exclusiveMinimum": 0
                            },
                            "relaxFlag": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "dataMap",
                            "fileName",
                            "address",
                            "relaxFlag"
                        ]
                    }
                }
            ]
        },
        "creationProperties": {
            "type": "object",
            "properties": {
                "chunkStorageConfig": {
                    "type": "object",
                    "properties": {
                        "chunkStorageBTreeHalfRank": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    },
                    "required": [
                        "chunkStorageBTreeHalfRank"
                    ]
                },
                "freeListConfig": {
                    "type": "object",
                    "properties": {
                        "freeListVersion": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "freeListVersion"
                    ]
                },
                "sizeConfig": {
                    "type": "object",
                    "properties": {
                        "lengthSizeInBytes": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "offsetSizeInBytes": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    },
                    "required": [
                        "lengthSizeInBytes",
                        "offsetSizeInBytes"
                    ]
                },
                "sohmConfig": {
                    "type": "object",
                    "properties": {
                        "maxList": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "minBTree": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "version": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "indexes": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "description": "HDF5 shared object header message (SOHM) index.",
                                "type": "object",
                                "properties": {
                                    "minMessageSize": {
                                        "type": "integer",
                                        "exclusiveMinimum": 0
                                    },
                                    "messageTypes": {
                                        "type": "array",
                                        "minItems": 1,
                                        "items": {
                                            "type": "string",
                                            "enum": [
                                                "H5O_SHMESG_ATTR_FLAG",
                                                "H5O_SHMESG_DTYPE_FLAG",
                                                "H5O_SHMESG_FILL_FLAG",
                                                "H5O_SHMESG_PLINE_FLAG",
                                                "H5O_SHMESG_SDSPACE_FLAG"
                                            ]
                                        }
                                    }
                                },
                                "required": [
                                    "minMessageSize",
                                    "messageTypes"
                                ]
                            }
                        }
                    },
                    "required": [
                        "maxList",
                        "minBTree",
                        "version",
                        "indexes"
                    ]
                },
                "superBlockVersion": {
                    "type": "integer",
                    "minimum": 0
                },
                "symbolTableConfig": {
                    "type": "object",
                    "properties": {
                        "nodeSize": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "treeRank": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "version": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "nodeSize",
                        "treeRank",
                        "version"
                    ]
                }
            }
        },
        "groups": {
            "description": "All groups in HDF5 file.",
            "type": "object",
            "$ref": "group.schema.json#/$defs/group"
        },
        "datasets": {
            "description": "All datasets in HDF5 file.",
            "type": "object",
            "$ref": "dataset.schema.json#/$defs/dataset"
        },
        "datatypes": {
            "description": "All committed datatypes in HDF5 file.",
            "type": "object",
            "$ref": "datatypes.schema.json#/$defs/committed"
        }
    }
}

=== HDFGroup/hdf5-json/data/json/scalar.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "7b128ec5-4a9d-11e5-883f-3c15c2da029e": {
            "alias": [
                "/0d"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SCALAR"
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": 42
        }, 
        "7b12b7fa-4a9d-11e5-bc9b-3c15c2da029e": {
            "alias": [
                "/0ds"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_ALLOC", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SCALAR"
            }, 
            "type": {
                "charSet": "H5T_CSET_ASCII", 
                "class": "H5T_STRING", 
                "length": "H5T_VARIABLE", 
                "strPad": "H5T_STR_NULLTERM"
            }, 
            "value": "hello"
        }, 
        "7b12ce17-4a9d-11e5-bfc6-3c15c2da029e": {
            "alias": [
                "/1d"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    1
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                42
            ]
        }, 
        "7b12e391-4a9d-11e5-b0c4-3c15c2da029e": {
            "alias": [
                "/1ds"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_ALLOC", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    1
                ]
            }, 
            "type": {
                "charSet": "H5T_CSET_ASCII", 
                "class": "H5T_STRING", 
                "length": "H5T_VARIABLE", 
                "strPad": "H5T_STR_NULLTERM"
            }, 
            "value": [
                "hello"
            ]
        }
    }, 
    "groups": {
        "7b117ffd-4a9d-11e5-865c-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "attributes": [
                {
                    "name": "attr1", 
                    "shape": {
                        "class": "H5S_SCALAR"
                    }, 
                    "type": {
                        "base": "H5T_STD_I64LE", 
                        "class": "H5T_INTEGER"
                    }, 
                    "value": 42
                }, 
                {
                    "name": "attr2", 
                    "shape": {
                        "class": "H5S_SCALAR"
                    }, 
                    "type": {
                        "charSet": "H5T_CSET_ASCII", 
                        "class": "H5T_STRING", 
                        "length": "H5T_VARIABLE", 
                        "strPad": "H5T_STR_NULLTERM"
                    }, 
                    "value": "hello"
                }
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7b128ec5-4a9d-11e5-883f-3c15c2da029e", 
                    "title": "0d"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7b12b7fa-4a9d-11e5-bc9b-3c15c2da029e", 
                    "title": "0ds"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7b12ce17-4a9d-11e5-bfc6-3c15c2da029e", 
                    "title": "1d"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7b12e391-4a9d-11e5-b0c4-3c15c2da029e", 
                    "title": "1ds"
                }
            ]
        }
    }, 
    "root": "7b117ffd-4a9d-11e5-865c-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/opaque_attr.json
{
    "apiVersion": "1.1.1",
    "datasets": {
        "83fefa97-82b10ff9-5f45-da0a54-668d61": {
            "alias": [
                "/DS1"
            ],
            "attributes": [
                {
                    "encoding": "base64",
                    "name": "A1",
                    "shape": {
                        "class": "H5S_SIMPLE",
                        "dims": [
                            4
                        ]
                    },
                    "type": {
                        "class": "H5T_OPAQUE",
                        "size": 7
                    },
                    "value": [
                        "T1BBUVVFMA==",
                        "T1BBUVVFMQ==",
                        "T1BBUVVFMg==",
                        "T1BBUVVFMw=="
                    ]
                }
            ],
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE",
                "fillTime": "H5D_FILL_TIME_IFSET",
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            },
            "shape": {
                "class": "H5S_NULL"
            },
            "type": {
                "base": "H5T_STD_I32LE",
                "class": "H5T_INTEGER"
            }
        }
    },
    "groups": {
        "83fefa97-82b10ff9-0b76-721f0a-398771": {
            "alias": [
                "/"
            ],
            "links": [
                {
                    "class": "H5L_TYPE_HARD",
                    "collection": "datasets",
                    "id": "83fefa97-82b10ff9-5f45-da0a54-668d61",
                    "title": "DS1"
                }
            ]
        }
    },
    "root": "83fefa97-82b10ff9-0b76-721f0a-398771"
}

=== HDFGroup/hdf5-json/data/json/compound_array_attr.json
{
    "apiVersion": "1.1.1",
    "datasets": {
        "dd3c0639-08f44d29-06b9-a92530-a0d73b": {
            "alias": [
                "/DS1"
            ],
            "attributes": [
                {
                    "name": "A1",
                    "shape": {
                        "class": "H5S_SCALAR"
                    },
                    "type": {
                        "class": "H5T_COMPOUND",
                        "fields": [
                            {
                                "name": "temp",
                                "type": {
                                    "base": "H5T_IEEE_F64LE",
                                    "class": "H5T_FLOAT"
                                }
                            },
                            {
                                "name": "2x2",
                                "type": {
                                    "base": {
                                        "base": "H5T_IEEE_F32LE",
                                        "class": "H5T_FLOAT"
                                    },
                                    "class": "H5T_ARRAY",
                                    "dims": [
                                        2,
                                        2
                                    ]
                                }
                            }
                        ]
                    },
                    "value": [
                        3.12,
                        [
                            [
                                -1.0,
                                1.0
                            ],
                            [
                                -2.0,
                                2.0
                            ]
                        ]
                    ]
                }
            ],
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE",
                "fillTime": "H5D_FILL_TIME_IFSET",
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            },
            "shape": {
                "class": "H5S_NULL"
            },
            "type": {
                "base": "H5T_STD_I32LE",
                "class": "H5T_INTEGER"
            }
        }
    },
    "groups": {
        "dd3c0639-08f44d29-55b4-8eb180-7cc5a1": {
            "alias": [
                "/"
            ],
            "links": [
                {
                    "class": "H5L_TYPE_HARD",
                    "collection": "datasets",
                    "id": "dd3c0639-08f44d29-06b9-a92530-a0d73b",
                    "title": "DS1"
                }
            ]
        }
    },
    "root": "dd3c0639-08f44d29-55b4-8eb180-7cc5a1"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_transform.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "795f6bcf-4a9d-11e5-b975-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4, 
                    7
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    1, 
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5
                ], 
                [
                    1, 
                    1, 
                    1, 
                    1, 
                    1, 
                    1, 
                    1
                ], 
                [
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7
                ], 
                [
                    1, 
                    3, 
                    5, 
                    7, 
                    9, 
                    11, 
                    13
                ]
            ]
        }
    }, 
    "groups": {
        "795df7b3-4a9d-11e5-9946-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "795f6bcf-4a9d-11e5-b975-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "795df7b3-4a9d-11e5-9946-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_unlimmod.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "79ac3ab3-4a9d-11e5-b858-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_INCR", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CHUNKED", 
                    "dims": [
                        4, 
                        4
                    ]
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    6, 
                    10
                ], 
                "maxdims": [
                    0, 
                    0
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ]
            ]
        }
    }, 
    "groups": {
        "79ab0dde-4a9d-11e5-9a75-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "79ac3ab3-4a9d-11e5-b858-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "79ab0dde-4a9d-11e5-9a75-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/null_objref_dset.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "79f6b0ae-4a9d-11e5-8d7b-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    1
                ]
            }, 
            "type": {
                "base": "H5T_STD_REF_OBJ", 
                "class": "H5T_REFERENCE"
            }, 
            "value": [
                "null"
            ]
        }
    }, 
    "groups": {
        "79f59b45-4a9d-11e5-a2d0-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "79f6b0ae-4a9d-11e5-8d7b-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "79f59b45-4a9d-11e5-a2d0-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_alloc.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "77ffa578-4a9d-11e5-9dd9-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4, 
                    7
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5, 
                    -6
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6
                ], 
                [
                    0, 
                    2, 
                    4, 
                    6, 
                    8, 
                    10, 
                    12
                ]
            ]
        }, 
        "77ffbbb3-4a9d-11e5-a650-3c15c2da029e": {
            "alias": [
                "/DS2"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_EARLY", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4, 
                    7
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5, 
                    -6
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6
                ], 
                [
                    0, 
                    2, 
                    4, 
                    6, 
                    8, 
                    10, 
                    12
                ]
            ]
        }
    }, 
    "groups": {
        "77fe93c2-4a9d-11e5-8562-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "77ffa578-4a9d-11e5-9dd9-3c15c2da029e", 
                    "title": "DS1"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "77ffbbb3-4a9d-11e5-a650-3c15c2da029e", 
                    "title": "DS2"
                }
            ]
        }
    }, 
    "root": "77fe93c2-4a9d-11e5-8562-3c15c2da029e"
}
